#!/bin/bash

RUNTIME="dnx-mono.1.0.0-rc2-16444"
# Enable if you wish to run on coreclr
#if [[ "$OSTYPE" == "linux-gnu" ]]; then
#  RUNTIME="dnx-coreclr-linux-x64.1.0.0-rc2-16444"
#elif [[ "$OSTYPE" == "darwin"* ]]; then
#  RUNTIME="dnx-coreclr-darwin-x64.1.0.0-rc2-16444"
#fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

BOOTSTRAP=$("$HOME/.dnx/runtimes/$RUNTIME/bin/dnx" -p "$DIR/../src/OmniSharp" run "$@")
if test -e "$BOOTSTRAP/project.lock.json";then
  "$HOME/.dnx/runtimes/$RUNTIME/bin/dnu" restore "$BOOTSTRAP"
fi
"$HOME/.dnx/runtimes/$RUNTIME/bin/dnx" "$BOOTSTRAP" -p run "$@"
