name: "Build"
env:
  Artifacts: ${{ github.workspace }}/artifacts/
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  CLR_OPENSSL_VERSION_OVERRIDE: 1.1
defaults:
  run:
    shell: pwsh
on:
  pull_request:
    branches:
      - master
      - feature/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-15-intel]
    name: "Build"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: "0"

      - name: Setup build environment
        uses: ./.github/actions/setup-build
        with:
          install-mono: ${{ startsWith(matrix.os, 'macos-') }}

      - name: Build and package
        run: |
          dotnet cake --configuration=Release --verbosity=Verbose --target=CI --publish-all --archive --use-global-dotnet-sdk

      - name: ⬆ Publish Logs
        uses: actions/upload-artifact@v4
        continue-on-error: true
        if: ${{ always() }}
        with:
          name: "logs-${{ github.workflow }}-${{ matrix.os }}"
          path: "${{ env.Artifacts }}/logs/"

      - name: ⬆ Publish Packages
        uses: actions/upload-artifact@v4
        with:
          name: "packages-${{ matrix.os }}"
          path: "${{ env.Artifacts }}/package/"

      - name: ⬆ Publish Deployment
        uses: actions/upload-artifact@v4
        with:
          name: "deployment-${{ matrix.os }}"
          path: "${{ env.Artifacts }}/deployment/"

      - name: ⬆ Publish NuGet
        uses: actions/upload-artifact@v4
        with:
          name: "nuget-${{ matrix.os }}"
          path: "${{ env.Artifacts }}/nuget/"

      - name: ⬆ Publish Scripts
        uses: actions/upload-artifact@v4
        with:
          name: "scripts-${{ matrix.os }}"
          path: "${{ env.Artifacts }}/scripts/"
