name: "Tests"
env:
  Artifacts: ${{ github.workspace }}/artifacts/
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  VSTEST_TESTHOST_SHUTDOWN_TIMEOUT: "1000"
defaults:
  run:
    shell: pwsh
on:
  pull_request:
    branches:
      - master
      - feature/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-15-intel, macos-latest]
        framework: [net10.0, net472]
        tests:
          - name: project-systems
            projects: OmniSharp.MSBuild.Tests,OmniSharp.Roslyn.CSharp.Tests,OmniSharp.DotNetTest.Tests,OmniSharp.Cake.Tests
          - name: hosts
            projects: OmniSharp.Lsp.Tests,OmniSharp.Script.Tests,OmniSharp.Tests,OmniSharp.Stdio.Tests,OmniSharp.Http.Tests
        exclude:
          - os: macos-15-intel
            framework: net10.0
          - os: macos-latest
            framework: net472
    name: "Test (${{ matrix.framework }}, ${{ matrix.os }}, ${{ matrix.tests.name }})"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: "0"

      - name: Setup test environment
        uses: ./.github/actions/setup-build
        with:
          compatibility-sdks: "true"
          install-mono: ${{ startsWith(matrix.os, 'macos-') }}

      - name: Build tests and prepare assets
        run: |
          dotnet cake --configuration=Release --verbosity=Verbose --target=PrepareTests --use-global-dotnet-sdk

      - name: Run tests
        uses: nick-invision/retry@v2
        with:
          shell: bash
          timeout_minutes: 40
          max_attempts: 3
          retry_on: error
          command: |
            dotnet cake --configuration=Release --verbosity=Verbose --target=RunTests --test-framework="$TEST_FRAMEWORK" --test-project="$TEST_PROJECT" --use-global-dotnet-sdk
        env:
          TEST_FRAMEWORK: ${{ matrix.framework }}
          TEST_PROJECT: ${{ matrix.tests.projects }}

      - name: ⬆ Publish Logs
        uses: actions/upload-artifact@v4
        continue-on-error: true
        if: ${{ always() }}
        with:
          name: "logs-${{ matrix.framework }}-${{ matrix.os }}-${{ matrix.tests.name }}"
          path: "${{ env.Artifacts }}/logs/"
